name: Development Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    strategy:
        matrix:
            node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
            node-version: ${{ matrix.node-version }}
    - name: Run Lint
      run: npm install
      run: npm run lint

  test:
    strategy:
        matrix:
            node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Tests
      run: npm install  
      run: npm test

  verify:
     runs-on: ubuntu-latest
     strategy:
        matrix:
            node-version: [18.x]
     env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    -  name: Install Node ${{ matrix.node-version }} 
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }} 
    - run: npm install
    - run: npm -g install snyk
    - run: snyk test
    - run: snyk monitor

